<div class="content-wrapper">
	<section class="content-header">
			<h2>Pseudonym Batch</h2>
	</section>
	<section class="content">

		<div class="row">
			<div class="col-md-11">
				<div class="box box-primary">
					<div class="box-body">
						<form class="form-horizontal" onsubmit="return false">

                <div class="form-group">
                  <label class="col-md-3 control-label">
										Use Encryption Key
									</label>
                  <div class="col-md-9">
										<div class="radio" style="padding-top:0px;">
											<label> <input type="radio" name="use_encryption_key" value="true" style="width:15px; height:15px;"/> True </label>
											<label style="margin-left:35px"> <input type="radio" name="use_encryption_key" value="false" style="width:15px; height:15px;" checked /> False </label>
										</div>	
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										Hash Type
									</label>
                  <div class="col-md-9">
										<div class="radio" style="padding-top:0px;">
											<label> <input type="radio" name="hash_type" value="2" style="width:15px; height:15px;" checked /> Standard </label>
											<label style="margin-left:35px"> <input type="radio" name="hash_type" value="1" style="width:15px; height:15px;" /> Draft </label>
										</div>	
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										Issuer Cert
									</label>
                  <div class="col-md-9">
										<select class="form-control select2-issuer-cert" name="issuer_cert">
											<option></option>
											<optgroup label="PCA cert list">
										<?php
										foreach($dir_list as $val){
												echo "<option value='".$val."'>".$val."/pca.cert</option>";		
										}
										?>
											</optgroup>
										</select>
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										OBE ID
									</label>
                  <div class="col-md-9">
										<!-- input type="text" class="form-control" name="obe_id" value="SAMPLE_PSEUDONYM_1" -->
										<select class="form-control select2-obeEnrol-cert" name="obe_id">
											<option></option>
											<optgroup label="OBE Enrol cert list">
										<?php
										foreach($dir_list_obe as $val1){
												echo "<option value='".$val1."'>.../".$val1."</option>";		
										}
										?>
											</optgroup>
										</select>
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										J Count
									</label>
                  <div class="col-md-9">
										<input type="number" class="form-control" name="j_count" min=1 value="20">
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										Craca ID
									</label>
                  <div class="col-md-9">
										<input type="text" class="form-control" name="craca_id" readonly placeholder="Please select issuer cert">
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										CRL Series
									</label>
                  <div class="col-md-9">
										<select class="form-control select2-crl-series" name="crl_series">
											<option></option>
											<optgroup label="CRL Series List">
												<option value="4">EeEnrollmentCrlSeries: 4</option>
												<option value="3">EeNonPseudonymCrlSeries: 3</option>
												<option value="1" selected>ObePseudonymCrlSeries: 1</option>
												<option value="2">ScmsComponentCrlSeries: 2</option>
												<option value="256">ScmsSpclComponentCrlSeries: 256</option>
											</optgroup>
										</select>
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										Batch Validity Period
									</label>
                  <div class="col-md-9">
										<div class="row">
											<div class="col-md-7">
												<div class="input-group">
													<input type="text" class="form-control" id="input_daterange" name="start_date" readonly>
													<div class="input-group-addon" id="daterange-btn">
														<i class="fa fa-calendar"></i>
													</div>
												</div>
											</div>
											<div class="col-md-5">
												<select class="form-control select2-duration" name="validity_period">
													<option></option>
													<optgroup label="Duration">
														<option value="1">1 year</option>
														<option value="2">2 years</option>
														<option value="3" selected>3 years</option>
														<option value="4">4 years</option>
														<option value="5">5 years</option>
														<option value="6">6 years</option>
														<option value="7">7 years</option>
														<option value="8">8 years</option>
														<option value="9">9 years</option>
														<option value="10">10 years</option>
													</optgroup>
												</select>
											</div>
										</div>
                  </div>
                </div>


                <div class="form-group">
                  <label class="col-md-3 control-label">
										Unit Cert Duration
									</label>
                  <div class="col-md-9">
										<div class="row">
											<div class="col-md-6">
												<input type="number" name="unit_value" class="form-control" min=1 max=52 placeholder="Weeks" style="width:100%" value="1">
											</div>
											<div class="col-md-6">
												<input type="number" name="unit_margin_value" class="form-control" min=0 placeholder="Margin HOURS" value="1">
											</div>
										</div>
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										App Permissions
									</label>
                  <div class="col-md-9">
										<button class="btn btn-primary action_app_permissions_add">Add</button>

										<div class="input-group" style="margin-top:3px;">
											<span class="input-group-addon"><span class="app_per_no">1</span>.</span>
											<select class="form-control select2-psid" name="app_permissions_psid" style="width:70%">
												<option></option>
												<optgroup label="App Permissions PSID">
													<option value="32" selected>[0x20] BsmPsid: 32</option>
													<option value="35">[0x23] SecurityMgmtPsid: 35</option>
													<option value="38">[0x26] MisbehaviorReportingPsid: 38</option>
													<option value="128">[0x80] DifferentialGpsCorrectionsUncompressedPsid: 128</option>
													<option value="129">[0x81] DifferentialGpsCorrectionsCompressedPsid: 129</option>
													<option value="130">[0x82] IntersectionSafetyAndAwarenessPsid: 130</option>
													<option value="131">[0x83] TravellerInformationAndRoadsideSignagePsid: 131</option>
													<option value="135">[0x87] WaveServiceAdvertisementPsid: 135</option>
													<option value="156">[0x88] PeerToPeerCertDistributionPsid: 136</option>
												</optgroup>
											</select>
											<input type="text" class="form-control col-md-2 pull-right" name="app_permissions_ssp" placeholder="ssp" style="width:30%;" value="8000">
											<span class="input-group-addon" style="padding:0px; border:none">&nbsp;<button class="btn btn-sm btn-danger action_app_permissions_remove" disabled><i class="fa fa-remove"></i></button></span>
										</div>

										<div class="input-group" style="margin-top:3px;">
											<span class="input-group-addon"><span class="app_per_no">2</span>.</span>
											<select class="form-control select2-psid" name="app_permissions_psid" style="width:70%">
												<option></option>
												<optgroup label="App Permissions PSID">
													<option value="32">[0x20] BsmPsid: 32</option>
													<option value="35">[0x23] SecurityMgmtPsid: 35</option>
													<option value="38" selected>[0x26] MisbehaviorReportingPsid: 38</option>
													<option value="128">[0x80] DifferentialGpsCorrectionsUncompressedPsid: 128</option>
													<option value="129">[0x81] DifferentialGpsCorrectionsCompressedPsid: 129</option>
													<option value="130">[0x82] IntersectionSafetyAndAwarenessPsid: 130</option>
													<option value="131">[0x83] TravellerInformationAndRoadsideSignagePsid: 131</option>
													<option value="135">[0x87] WaveServiceAdvertisementPsid: 135</option>
													<option value="156">[0x88] PeerToPeerCertDistributionPsid: 136</option>
												</optgroup>
											</select>
											<input type="text" class="form-control col-md-2 pull-right" name="app_permissions_ssp" placeholder="ssp" style="width:30%;" value="8000">
											<span class="input-group-addon" style="padding:0px; border:none">&nbsp;<button class="btn btn-sm btn-danger action_app_permissions_remove" disabled><i class="fa fa-remove"></i></button></span>
										</div>
									</div>
								</div>
						</form>
					</div>


					<div class="box-footer">
						<button class="btn btn-md btn-primary pull-right action_submit">발급하기</button>
						<button class="btn btn-md btn-warning pull-right action_loading" style="display:none;cursor:default"><i class="fa fa-refresh fa-spin"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;발급중</button>
					</div>

				</div>
			</div>
		</div>

		<div class="row" id="callouts-fail" style="display:none">
			<div class="col-md-9">
				 <div class="alert alert-danger alert-dismissible">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<h4><i class="icon fa fa-ban"></i> 실패!</h4>
						인증서 발급에 실패하였습니다. <br /><br />
						<p>
							message: <br />
							Danger alert preview. This alert is dismissable. A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.
						</p>
					</div>
			</div>
		</div>
		<div class="row" id="callouts-success" style="display:none">
			<div class="col-md-9">
				 <div class="alert alert-success alert-dismissible">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<h4><i class="icon fa fa-check"></i> 완료!</h4>
						인증서를 발급하였습니다. <br /><br />
						<p class="success_message">
						</p>
					</div>
			</div>
		</div>
	</section>
</div>

<script src="/assets/js/issued/pseudonymBatch.js"></script>
