<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			Autocrypt CertIssue - 2016
			<small>for KATECH</small>
		</h1>
		<!-- ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li class="active">navigation</li>
		</ol -->
	</section>


	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-12">

						<div class="box box-default color-palette-box">
							<div class="box-header with-border">
								<h3 class="box-title"><i class="fa fa-certificate"></i> Select Mode</h3>
							</div>

							<div class="box-body" style="padding:35px 0px;">
								<div class="row">
									<div class="col-md-3"></div>
									<div class="col-md-6">
										<a href="http://<?=str_replace(":16089", "", $_SERVER["HTTP_HOST"])?>:16088/"	class="btn btn-primary btn-lg pull-left">CertTool 2013</a>	
										<a href="#"						class="btn btn-primary btn-lg pull-right">CertTool 2016</a>	
									</div>
									<div class="col-md-3"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- //col-md-12 -->
		</div>
</div>
