<div class="content-wrapper">
	<section class="content-header">
			<h2>PG</h2>
	</section>
	<section class="content">

		<div class="row">
			<div class="col-md-11">
				<div class="box box-primary">
					<div class="box-body">
						<form class="form-horizontal" onsubmit="return false">

                <div class="form-group">
                  <label class="col-md-3 control-label">
										Cert Type
									</label>
                  <div class="col-md-9">
										<input type="text" class="form-control" name="cert_type" value="explicit" disabled>
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										Use Encryption Key
									</label>
                  <div class="col-md-9">
										<div class="radio" style="padding-top:0px;">
											<label> <input type="radio" name="use_encryption_key" value="true" style="width:15px; height:15px;"/> True </label>
											<label style="margin-left:35px"> <input type="radio" name="use_encryption_key" value="false" style="width:15px; height:15px;" checked /> False </label>
										</div>	
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										Issuer Cert
									</label>
                  <div class="col-md-9">
										<select class="form-control select2-issuer-cert" name="issuer_cert">
											<option></option>
											<optgroup label="Root CA cert list">
										<?php
										foreach($dir_list as $val){
												echo "<option value='".$val."'>".$val."/rootca.cert</option>";		
										}
										?>
											</optgroup>
										</select>
									</div>
								</div>
							
                <div class="form-group">
                  <label class="col-md-3 control-label">
										Cert ID
									</label>
                  <div class="col-md-9">
										<div class="row">
											<div class="col-md-3">
												<input type="text" class="form-control col-md-2" name="cert_id_type" placeholder="type">
											</div>
											<div class="col-md-9">
												<input type="text" class="form-control col-md-2" name="cert_id_value" placeholder="value">
											</div>
										</div>
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										Craca ID
									</label>
                  <div class="col-md-9">
										<input type="text" class="form-control" name="craca_id">
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										CRL Series
									</label>
                  <div class="col-md-9">
										<select class="form-control select2-crl-series" name="crl_series">
											<option></option>
											<optgroup label="CRL Series List">
												<option value="4">EeEnrollmentCrlSeries: 4</option>
												<option value="3">EeNonPseudonymCrlSeries: 3</option>
												<option value="1">ObePseudonymCrlSeries: 1</option>
												<option value="2">ScmsComponentCrlSeries: 2</option>
												<option value="256">ScmsSpclComponentCrlSeries: 256</option>
											</optgroup>
										</select>
									</div>
								</div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										Validity Period
									</label>
                  <div class="col-md-9">
										<div class="row">
											<div class="col-md-7">
												<div class="input-group">
													<input type="text" class="form-control" id="input_daterange" name="start_date" readonly>
													<div class="input-group-addon" id="daterange-btn">
														<i class="fa fa-calendar"></i>
													</div>
												</div>
											</div>
											<div class="col-md-5">
												<input type="number" class="form-control" name="duration" min="1" placeholder="Duration HOURS">
											</div>
										</div>
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
										App Permissions
									</label>
                  <div class="col-md-9">
										<button class="btn btn-primary action_app_permissions_add">Add</button>

										<div class="input-group" style="margin-top:3px;">
											<span class="input-group-addon"><span class="app_per_no">1</span>.</span>
											<select class="form-control select2-psid" name="app_permissions_psid" style="width:70%">
												<option></option>
												<optgroup label="App Permissions PSID">
													<option value="32">[0x20] BsmPsid: 32</option>
													<option value="35">[0x23] SecurityMgmtPsid: 35</option>
													<option value="38">[0x26] MisbehaviorReportingPsid: 38</option>
													<option value="128">[0x80] DifferentialGpsCorrectionsUncompressedPsid: 128</option>
													<option value="129">[0x81] DifferentialGpsCorrectionsCompressedPsid: 129</option>
													<option value="130">[0x82] IntersectionSafetyAndAwarenessPsid: 130</option>
													<option value="131">[0x83] TravellerInformationAndRoadsideSignagePsid: 131</option>
													<option value="135">[0x87] WaveServiceAdvertisementPsid: 135</option>
													<option value="156">[0x88] PeerToPeerCertDistributionPsid: 136</option>
												</optgroup>
											</select>
											<input type="text" class="form-control col-md-2 pull-right" name="app_permissions_ssp" placeholder="ssp" style="width:30%;">
											<span class="input-group-addon" style="padding:0px; border:none">&nbsp;<button class="btn btn-sm btn-danger action_app_permissions_remove" disabled><i class="fa fa-remove"></i></button></span>
										</div>
									</div>
								</div>
						</form>
					</div>


					<div class="box-footer">
						<button class="btn btn-md btn-primary pull-right action_submit">발급하기</button>
						<button class="btn btn-md btn-warning pull-right action_loading" style="display:none;cursor:default"><i class="fa fa-refresh fa-spin"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;발급중</button>
					</div>

				</div>
			</div>
		</div>

	</section>
</div>

<script src="/assets/js/issued/pg.js"></script>
